#!/usr/bin/env python3
# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



import time
from opentelemetry import metrics
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.tools.resource_detector import GoogleCloudResourceDetector
metrics.set_meter_provider(MeterProvider(stateful=False, resource=GoogleCloudResourceDetector().detect()))


from google.cloud import storage
client = storage.Client()
client.list_buckets()

bucket = client.get_bucket('fishbucket1')
for i in range(500):
    blob2 = bucket.blob('file')
    blob2.upload_from_string('hi')
    blob2.download_as_string()
    blob2.download_as_string()
    time.sleep(1)
    print(i)
